# Generated by Django 5.1.5 on 2025-08-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sectpipchion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prise',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='update',
            new_name='updated',
        ),
    ]
